import React, { lazy, useCallback, useEffect, useRef, useState } from 'react'
import OwnerAuth from './OwnerAuth.jsx'
import LazyBoundary from './LazyBoundary.jsx'
import OwnerWorkspace from './OwnerWorkspace.jsx'
import { deadlineGet, reviewTokenFromLocation } from './api.js'
import { initTheme } from './ThemeSwitcher.jsx'
import { initFx } from './fx.js'
import { initDensity } from './DensityToggle.jsx'
import { routeHashPath } from './runRouteState.js'
import { installationRouteLabel, isInstallationRouteView } from './globalNav.js'

const RunList = lazy(() => import('./RunList.jsx'))
const RunView = lazy(() => import('./RunView.jsx'))
const Settings = lazy(() => import('./Settings.jsx'))
const ResearchAtlas = lazy(() => import('./ResearchAtlas.jsx'))
const SharedAssistant = lazy(() => import('./SharedAssistant.jsx'))
const InstallationView = lazy(() => import('./InstallationView.jsx'))

initTheme()   // restore the saved design theme before first paint
initFx()      // restore the saved Energy/Reactor FX level (data-fx) before first paint
initDensity() // restore compact / comfortable density before first paint

// Tiny hash router. Two scopes, and the URL says which one you are in:
//   #/run/<id>…            — ONE run's workspace (its graph, trace, budget, cards)
//   #/ #/atlas #/memory #/knowledge #/gpu #/settings — the LoopLab plane, true for the installation
// The legacy #/research-atlas alias is replaced in place so links generated by the UI have one
// canonical form. #/memory, #/knowledge and #/gpu are the new homes of three panels that used to be
// reachable ONLY from inside a run's menu despite taking no run id; the run workspace still mounts
// them for existing `#/run/<id>?panel=memory|authoring|gpu` bookmarks (see globalNav.js). The
// assistant is NOT a route anymore — it's one persistent component (AssistantBar) with three views
// (bar/drawer/full) that stays mounted across every route, so its conversation is never reset by
// navigation.
const safeDecode = (s) => { try { return decodeURIComponent(s) } catch { return s } }
function parseHash() {
  if (/\/review\/?$/.test(location.pathname)) return { view: 'review', token: reviewTokenFromLocation() }
  const h = routeHashPath(location.hash)
  if (h === '#/settings') return { view: 'settings' }
  if (h === '#/research-atlas') return { view: 'research-atlas', canonicalHash: '#/atlas' }
  if (h === '#/atlas') return { view: 'research-atlas' }
  const installation = h.match(/^#\/([a-z]+)$/)
  if (installation && isInstallationRouteView(installation[1])) return { view: installation[1] }
  const sh = h.match(/^#\/assistant\/shared\/(.+)$/)
  if (sh) return { view: 'shared', id: safeDecode(sh[1]) }
  const m = h.match(/^#\/run\/(.+)$/)
  return m ? { view: 'run', id: safeDecode(m[1]) } : { view: 'list' }
}

const LIST_HISTORY_KEY = 'looplab.listNavigation'
const LIST_HISTORY_CACHE_LIMIT = 128
// Which list control the operator left FROM, so returning restores focus to it. `looplab` is the
// LoopLab menu that now owns every installation destination; `settings` is its predecessor and stays
// accepted because it is already written into operators' persisted history entries.
const LIST_ORIGIN_CONTROLS = new Set(['settings', 'looplab'])
// Leaving the list for another INSTALLATION surface keeps the list's saved scroll/filters and the
// control to return focus to; opening a run replaces the origin with that run.
const keepsListOrigin = view => view === 'list' || view === 'settings'
  || view === 'research-atlas' || isInstallationRouteView(view)
const listHistoryCache = new Map()
let listHistorySequence = 0

const normalizeListOriginControl = value => LIST_ORIGIN_CONTROLS.has(value) ? value : null

function rawListHistory() {
  const state = history.state
  if (!state || typeof state !== 'object' || Array.isArray(state)) return null
  const saved = state[LIST_HISTORY_KEY]
  return saved && typeof saved === 'object' && !Array.isArray(saved) ? saved : null
}

function nextListHistoryEntryId() {
  listHistorySequence += 1
  return `${Date.now().toString(36)}-${listHistorySequence.toString(36)}`
}

function cacheListHistory(entryId, navigation) {
  if (!entryId || !navigation || typeof navigation !== 'object' || Array.isArray(navigation)) return
  listHistoryCache.delete(entryId)
  listHistoryCache.set(entryId, navigation)
  while (listHistoryCache.size > LIST_HISTORY_CACHE_LIMIT) {
    listHistoryCache.delete(listHistoryCache.keys().next().value)
  }
}

function readListHistory() {
  const saved = rawListHistory()
  if (!saved) return null
  const entryId = typeof saved.entryId === 'string' && saved.entryId && saved.entryId.length <= 128
    ? saved.entryId : null
  const candidate = (entryId && listHistoryCache.get(entryId)) || saved.navigation
  const navigation = candidate && typeof candidate === 'object' && !Array.isArray(candidate)
    ? candidate : null
  return {
    ...saved,
    entryId,
    navigation,
    originRunId: typeof saved.originRunId === 'string' && saved.originRunId
      ? saved.originRunId : null,
    originControl: normalizeListOriginControl(saved.originControl),
  }
}

function writeListHistory(navigation, originRunId = null, originControl = null) {
  if (!navigation || typeof navigation !== 'object' || Array.isArray(navigation)) return
  try {
    const state = history.state && typeof history.state === 'object' && !Array.isArray(history.state)
      ? history.state : {}
    const current = rawListHistory()
    const entryId = typeof current?.entryId === 'string' && current.entryId && current.entryId.length <= 128
      ? current.entryId : nextListHistoryEntryId()
    cacheListHistory(entryId, navigation)
    history.replaceState({
      ...state,
      [LIST_HISTORY_KEY]: {
        navigation,
        originRunId: typeof originRunId === 'string' && originRunId ? originRunId : null,
        originControl: normalizeListOriginControl(originControl),
        entryId,
      },
    }, '', location.href)
  } catch { /* The in-memory snapshot remains authoritative if history state is unavailable. */ }
}

function cacheCurrentListHistory(navigation, originRunId = null, originControl = null) {
  const current = rawListHistory()
  const entryId = typeof current?.entryId === 'string' && current.entryId && current.entryId.length <= 128
    ? current.entryId : null
  if (entryId) {
    cacheListHistory(entryId, navigation)
    return
  }
  writeListHistory(navigation, originRunId, originControl)
}

function ReviewRoute({ token }) {
  const [resource, setResource] = useState({ status: 'loading', error: '' })
  const [retry, setRetry] = useState(0)
  useEffect(() => {
    let active = true
    if (!token) {
      setResource({ status: 'gone',
        error: 'Review link incomplete or invalid. Ask the owner for a new link.' })
      return () => { active = false }
    }
    setResource({ status: 'loading', error: '' })
    const timed = deadlineGet('/api/review', 12_000)
    timed.promise
      .then(data => { if (active) setResource({ status: 'ready', data, error: '' }) })
      .catch(error => {
        if (!active) return
        const gone = [401, 404, 410].includes(error?.status)
        setResource({ status: gone ? 'gone' : 'error',
          error: gone
            ? 'Review link invalid, expired, or revoked. Ask the owner for a new link.'
            : 'Review link unavailable. Retry.' })
      })
    return () => { active = false; timed.controller.abort() }
  }, [token, retry])
  useEffect(() => {
    const frame = requestAnimationFrame(() => {
      if (!document.querySelector('[aria-modal="true"]')) document.querySelector('[data-route-main]')?.focus()
    })
    return () => cancelAnimationFrame(frame)
  }, [resource.status])
  if (resource.status !== 'ready') return <main className="auth-gate" data-route-main tabIndex={-1} aria-live="polite">
    <div className="auth-card">
      <div className="auth-mark" aria-hidden="true">{resource.status === 'gone' ? '×' : '◉'}</div>
      <h1>{resource.status === 'loading' ? 'Opening review…' : resource.status === 'gone' ? 'Review link unavailable' : 'Could not open review'}</h1>
      <p>{resource.status === 'loading' ? 'Validating this read-only capability.' : resource.error}</p>
      {resource.status === 'error' && <button className="btn primary" onClick={() => setRetry(n => n + 1)}>Retry</button>}
    </div>
  </main>
  const reviewKey = `${resource.data.id || token}:${resource.data.run_id}`
  return <LazyBoundary label="run review" mode="route" focusOnReady resetKey={reviewKey}>
    <RunView key={reviewKey} runId={resource.data.run_id} onBack={null}
      reviewMode reviewMeta={resource.data} />
  </LazyBoundary>
}

function RouteFocus({ label, routeKey, children, autoFocus = true }) {
  useEffect(() => {
    document.title = `${label} · LoopLab`
    if (!autoFocus) return undefined
    const frame = requestAnimationFrame(() => {
      if (!document.querySelector('[aria-modal="true"]')) document.querySelector('[data-route-main]')?.focus()
    })
    return () => cancelAnimationFrame(frame)
  }, [routeKey, label, autoFocus])
  return <>
    <div className="sr-only" role="status" aria-live="polite" aria-atomic="true">{label}</div>
    {children}
  </>
}

export default function App() {
  const initialListHistoryRef = useRef()
  if (initialListHistoryRef.current === undefined) {
    initialListHistoryRef.current = readListHistory() || null
  }
  const listNavigationRef = useRef(initialListHistoryRef.current?.navigation || null)
  const listOriginRunRef = useRef(initialListHistoryRef.current?.originRunId || null)
  const listOriginControlRef = useRef(initialListHistoryRef.current?.originControl || null)
  const [route, setRoute] = useState(parseHash())
  useEffect(() => {
    const on = () => {
      const next = parseHash()
      const saved = readListHistory()
      if (saved?.navigation) {
        const keepsOrigin = keepsListOrigin(next.view)
        const originRunId = next.view === 'run' ? next.id
          : keepsOrigin ? saved.originRunId : null
        const originControl = keepsOrigin ? saved.originControl : null
        listNavigationRef.current = saved.navigation
        listOriginRunRef.current = originRunId
        listOriginControlRef.current = originControl
        // Materialize any newer entry-cache snapshot into the destination entry too. This keeps a
        // subsequent reload exact and normalizes origins copied by direct hash navigation.
        writeListHistory(saved.navigation, originRunId, originControl)
      } else if (listNavigationRef.current) {
        const keepsOrigin = keepsListOrigin(next.view)
        const originRunId = next.view === 'run' ? next.id
          : keepsOrigin ? listOriginRunRef.current : null
        const originControl = keepsOrigin ? listOriginControlRef.current : null
        listOriginRunRef.current = originRunId
        listOriginControlRef.current = originControl
        writeListHistory(listNavigationRef.current, originRunId, originControl)
      }
      setRoute(next)
    }
    window.addEventListener('hashchange', on)
    window.addEventListener('popstate', on)
    return () => {
      window.removeEventListener('hashchange', on)
      window.removeEventListener('popstate', on)
    }
  }, [])
  useEffect(() => {
    if (!route.canonicalHash || location.hash === route.canonicalHash) return
    try {
      history.replaceState(history.state, '', route.canonicalHash)
    } catch {
      // The legacy alias already renders its correct destination. If History is throttled, use a
      // same-document replacement when available and never let canonicalization crash the route.
      try { location.replace(route.canonicalHash) } catch { /* keep the working legacy URL */ }
    }
    if (location.hash === route.canonicalHash) setRoute(parseHash())
  }, [route.canonicalHash])
  const routeLabel = route.view === 'run' ? `Run ${route.id}`
    : route.view === 'settings' ? 'Settings'
    : route.view === 'research-atlas' ? 'Research Atlas preview'
    : route.view === 'shared' ? 'Shared Assistant chat'
    : route.view === 'review' ? 'Read-only run review'
    : isInstallationRouteView(route.view) ? installationRouteLabel(route.view) : 'Runs'
  const rememberListNavigation = useCallback((snapshot, options = null) => {
    if (snapshot && typeof snapshot === 'object' && !Array.isArray(snapshot)) {
      listNavigationRef.current = snapshot
      if (route.view === 'list') {
        const current = readListHistory()
        const originRunId = current && Object.prototype.hasOwnProperty.call(current, 'originRunId')
          ? current.originRunId : listOriginRunRef.current
        const originControl = current && Object.prototype.hasOwnProperty.call(current, 'originControl')
          ? current.originControl : listOriginControlRef.current
        if (options?.persist === false) cacheCurrentListHistory(snapshot, originRunId, originControl)
        else writeListHistory(snapshot, originRunId, originControl)
      }
    }
  }, [route.view])
  const finishListRestore = useCallback(snapshot => {
    if (snapshot && typeof snapshot === 'object' && !Array.isArray(snapshot)) {
      listNavigationRef.current = snapshot
    }
    listOriginRunRef.current = null
    listOriginControlRef.current = null
    writeListHistory(listNavigationRef.current, null, null)
  }, [])
  const navigateWithListState = useCallback((hash, snapshot, originRunId = null,
    originControl = null) => {
    const navigation = snapshot || listNavigationRef.current
    if (navigation) {
      listNavigationRef.current = navigation
      listOriginRunRef.current = originRunId
      listOriginControlRef.current = normalizeListOriginControl(originControl)
      writeListHistory(navigation, originRunId, originControl)
    }
    location.hash = hash
    if (navigation) writeListHistory(navigation, originRunId, originControl)
  }, [])
  const open = useCallback((id, snapshot, href = null) => {
    const runId = String(id)
    const target = typeof href === 'string' && href.startsWith('#/run/')
      ? href : `#/run/${encodeURIComponent(runId)}`
    navigateWithListState(target, snapshot, runId)
  }, [navigateWithListState])
  const back = useCallback(() => {
    location.hash = ''
    if (listNavigationRef.current) {
      writeListHistory(listNavigationRef.current, listOriginRunRef.current,
        listOriginControlRef.current)
    }
  }, [])
  // One departure for every LoopLab destination. The list's scroll/filter snapshot is preserved and
  // focus returns to the LoopLab menu, whichever installation surface was opened — previously only
  // Settings did this and Atlas silently dropped the operator's place in the list.
  const globalNavigate = useCallback((hash, snapshot) => {
    navigateWithListState(hash, snapshot, null, 'looplab')
  }, [navigateWithListState])
  const restoreListNavigation = route.view === 'list' && !!listNavigationRef.current

  // Public review/share views own the whole screen and return before any owner-plane component mounts.
  // Everywhere else (list / run / settings) the persistent assistant and attention inbox stay available.
  let content
  const routeKey = `${route.view}:${route.id || route.token || ''}`
  if (route.view === 'review') return <RouteFocus label={routeLabel} routeKey={routeKey}>
    <ReviewRoute key={route.token || 'invalid-review'} token={route.token} />
  </RouteFocus>
  // The shared read-only chat is a PUBLIC surface: the backend serves /api/assistant/shared/ WITHOUT
  // the owner token (server.py::_unauth_api_ok), so it must bypass the OwnerAuth unlock gate exactly
  // like the review route. Falling through into <OwnerAuth> made a token-protected deployment show
  // recipients the "Unlock LoopLab controls" screen instead of the chat, defeating the share link.
  if (route.view === 'shared') return <RouteFocus label={routeLabel} routeKey={routeKey}>
    <LazyBoundary key={routeKey} label="shared Assistant chat" mode="route" focusOnReady resetKey={routeKey}>
      <SharedAssistant sid={route.id} />
    </LazyBoundary>
  </RouteFocus>
  if (route.view === 'run') content = <LazyBoundary label={`run ${route.id}`} mode="route" focusOnReady resetKey={routeKey}>
    <RunView key={route.id} runId={route.id} onBack={back} />
  </LazyBoundary>
  else if (route.view === 'settings') content = <LazyBoundary label="settings" mode="route" focusOnReady resetKey={routeKey}>
    <Settings onBack={back} />
  </LazyBoundary>
  // Portfolio evidence is owner-only, so this experimental preview stays in the
  // authenticated owner plane and never mounts beside the public review/shared early returns above.
  else if (route.view === 'research-atlas') content = <LazyBoundary label="Research Atlas preview" mode="route" focusOnReady resetKey={routeKey}>
    <ResearchAtlas onBack={back} />
  </LazyBoundary>
  // Cross-run memory / authored knowledge / host GPU: installation surfaces that used to be reachable
  // only from a run's own menu even though none of them reads a run id.
  else if (isInstallationRouteView(route.view)) content = <LazyBoundary label={routeLabel} mode="route" focusOnReady resetKey={routeKey}>
    <InstallationView view={route.view} onBack={back} />
  </LazyBoundary>
  else content = <LazyBoundary label="runs" mode="route" focusOnReady={!restoreListNavigation} resetKey={routeKey}>
    <RunList initialNavigationState={listNavigationRef.current}
      restoreFocusRunId={listOriginRunRef.current}
      restoreFocusControl={listOriginControlRef.current}
      onNavigationStateChange={rememberListNavigation}
      onNavigationRestored={finishListRestore}
      onOpen={open} onGlobalNavigate={globalNavigate} />
  </LazyBoundary>

  return <OwnerAuth label={routeLabel}><RouteFocus label={routeLabel} routeKey={routeKey}
    autoFocus={!restoreListNavigation}>
    {/* OwnerWorkspace is stable across list/run/settings/Atlas changes. Its one Assistant instance keeps
        conversation and draft state; public review/share returns above before owner pollers mount. */}
    <OwnerWorkspace route={route}>{content}</OwnerWorkspace>
  </RouteFocus></OwnerAuth>
}
