// Translate known UI/contract wording only. Unknown server policy stays verbatim:
// an older/newer server restriction must never become a guessed permission.
const russian = {
  'Connect external agent': 'Подключить внешнего агента',
  'Use a stdio MCP client on a machine with LoopLab installed. The URL must be reachable from that client.': 'Откройте MCP-клиент на компьютере с установленным LoopLab. Сервер должен быть доступен с этого компьютера.',
  'Connection context unavailable. Refresh before copying.': 'Данные подключения недоступны. Обновите их перед копированием.',
  'Reading connection context…': 'Читаем данные подключения…',
  'Retry': 'Повторить чтение',
  'UI / API server': 'Сервер UI / API',
  'Run': 'Запуск',
  'Run root on server': 'Папка запусков на сервере',
  'Run directory': 'Папка этого запуска',
  'Engine probe': 'Состояние движка',
  'Unknown': 'Неизвестно',
  'Alive at last read': 'Работал при последнем чтении',
  'Stopped at last read': 'Остановлен при последнем чтении',
  ' · agent connection is not measured': ' · подключение агента не измеряется',
  '1. Configure the MCP process': '1. Настройте MCP-клиент',
  'MCP client ': 'MCP-клиент ',
  'Other MCP client': 'Другой MCP-клиент',
  'Copy MCP configuration': 'Скопировать конфигурацию MCP',
  'MCP configuration copied. Supply the scoped secret separately.': 'Конфигурация MCP скопирована. Передайте harness-токен отдельно.',
  'Clipboard unavailable. Select the configuration below and copy it manually.': 'Буфер обмена недоступен. Выделите конфигурацию выше и скопируйте вручную.',
  'Place this in a trusted project .codex/config.toml or your user config. env_vars forwards the scoped token from the Codex process environment.': 'Добавьте конфигурацию в .codex/config.toml доверенного проекта или в пользовательские настройки. env_vars передаёт harness-токен из окружения процесса Codex.',
  'Place this in your project .mcp.json. The token placeholder reads the scoped credential from the Claude process environment.': 'Добавьте конфигурацию в .mcp.json проекта. Значение токена берётся из окружения процесса Claude.',
  "This is a generic stdio descriptor; configure scoped credential forwarding in your client's environment settings.": 'Это общая конфигурация stdio. Настройте передачу harness-токена в параметрах окружения MCP-клиента.',
  ' The token value is not included.': ' Значение токена здесь отсутствует.',
  'For a virtual environment, set command to the full looplab executable path on the client machine. Supply the scoped credential and restart the client. harness-mcp refuses a missing token; it never falls back to owner access.': 'Для виртуального окружения укажите в command полный путь к looplab на компьютере клиента. Передайте harness-токен и перезапустите клиент. Без токена harness-mcp откажет в подключении; доступ владельца не подставляется.',
  '2. Supply the scoped credential separately': '2. Передайте harness-токен отдельно',
  'A harness credential is configured on this server.': 'На сервере настроен harness-токен.',
  'Operator setup required: this server has no scoped harness credential configured.': 'Нужна настройка оператором: на сервере отсутствует harness-токен.',
  '3. Connect and give the agent this run': '3. Подключите агента к этому запуску',
  'Open Claude interactively in that project and review its project MCP approval prompt. Pending approval means the MCP process has not connected yet.': 'Откройте Claude в проекте и проверьте запрос разрешения на MCP. Пока разрешение ожидается, процесс MCP ещё не подключён.',
  'Open Codex in a trusted project and inspect /mcp to confirm that looplab loaded.': 'Откройте Codex в доверенном проекте. Проверьте через /mcp, что looplab загружен.',
  'Inspect the MCP server status in your client.': 'Проверьте состояние MCP-сервера в клиенте.',
  ' Connected confirms the stdio process only. Tool calls can still need client approval. Use connection_check for this run and inspect its result.': ' Статус Connected подтверждает только процесс stdio. Вызовы инструментов могут требовать отдельного разрешения клиента. Выполните connection_check для этого запуска и проверьте результат.',
  ' In Claude --print, exit 0 can include permission_denials.': ' В Claude --print даже exit 0 может сопровождаться permission_denials.',
  'Copy agent instruction': 'Скопировать инструкцию агенту',
  'Agent instruction copied. Supply the scoped secret separately.': 'Инструкция скопирована. Передайте harness-токен отдельно.',
  'Clipboard unavailable. Select the instruction below and copy it manually.': 'Буфер обмена недоступен. Выделите инструкцию ниже и скопируйте вручную.',
  'Preview instruction and workspace permissions': 'Инструкция и границы изменения кода',
  'Copying starts no work. Reconnect here with current state, receipts and checkpoints.': 'Копирование не запускает работу. Для продолжения прочитайте актуальное состояние, квитанции и вопросы оценки.',
  'Reconnect or recover a lost response': 'Продолжить работу после потери подключения или ответа',
  'Keep this run. Read current state and generation; connecting MCP does not restart a stopped engine.': 'Продолжайте этот запуск. Прочитайте состояние и generation; подключение MCP не перезапускает остановленный движок.',
  'Observe the original command receipt, then inspect events and node results. The command may already have applied.': 'Прочитайте исходную квитанцию команды, затем события и результаты. Команда могла уже выполниться.',
  'Read Agent cycle and checkpoints, including questions opened after the evaluator exits.': 'Прочитайте Agent cycle и вопросы оценки, включая появившиеся после завершения процесса оценки.',
  'Choose an explicit continuation, pause or finish. A quiet log does not prove that an agent died.': 'Явно выберите продолжение, паузу или завершение. Тишина в журнале не доказывает гибель агента.',
  'Find original command by': 'Найти исходную команду по',
  'Original Idempotency-Key': 'Исходный Idempotency-Key',
  'Command ID': 'ID команды',
  'Read saved receipt': 'Прочитать сохранённую квитанцию',
  'Key verification is unavailable in this browser. Read by the original Command ID from Events.': 'Проверка ключа недоступна в этом браузере. Найдите исходный Command ID в Events и прочитайте квитанцию по нему.',
  "One read only. No worker restart, command retry or resume. The key is sent in a header and kept only in this form's memory.": 'Только чтение: без перезапуска worker, повтора команды или возобновления запуска. Ключ передаётся в заголовке и хранится только в памяти этой формы.',
  'No original identity? Inspect Events for command_id. Do not invent a fresh key for an uncertain request.': 'Нет исходного ID или ключа? Найдите command_id в Events. Не создавайте новый ключ для запроса с неизвестным исходом.',
  'Reading saved receipt…': 'Читаем сохранённую квитанцию…',
  'Receipt unavailable or changed. Read current state and evidence; absence does not prove no action occurred.': 'Квитанция недоступна или изменилась. Прочитайте актуальное состояние и доказательства; отсутствие ответа не означает, что действие не выполнялось.',
  'Saved command receipt': 'Сохранённая квитанция команды',
  'Command receipt is terminal; this does not prove an experiment evaluated.': 'Команда завершена; это не доказывает, что эксперимент прошёл оценку.',
  'Nonterminal receipt. Reading it did not continue the command.': 'Команда не завершена. Чтение квитанции не продолжило её выполнение.',
  'Recorded intent event #': 'Записанное событие намерения №',
  '; verify it in Events.': '; проверьте его в Events.',
  'Error code: ': 'Код ошибки: ',
  'The receipt permits considering an explicit retry after checking current evidence.': 'Квитанция допускает рассмотрение явного повтора после проверки актуальных доказательств.',
  'No retry permission recorded.': 'Разрешение на повтор не записано.',
  'Saved snapshot may lag events. GET /commands/{command_id} can restart a nonterminal worker; choose that recovery deliberately. Preserve the original payload and key for an exact lost-response resubmission.': 'Сохранённая квитанция может отставать от событий. GET /commands/{command_id} может перезапустить незавершённый worker; выбирайте такое восстановление явно. Для точного повтора после потери ответа сохраните исходные тело запроса и ключ.',
  'Use only a distinct LOOPLAB_HARNESS_TOKEN in the MCP process; remove LOOPLAB_UI_TOKEN from its environment. Pass the secret separately through the client\'s protected credential mechanism.': 'Используйте отдельный LOOPLAB_HARNESS_TOKEN в процессе MCP; удалите LOOPLAB_UI_TOKEN из его окружения. Передайте секрет отдельно через защищённый механизм учётных данных клиента.',
  'The harness token controls launched external runs on this server and has limited controls on internal runs; it is not restricted to this run. Prefer a separate server/run root for external work.': 'Harness-токен управляет запущенными внешними ранами на этом сервере и имеет ограниченные права на внутренние раны. Он не ограничен одним запуском. Для внешнего агента предпочтителен отдельный сервер и папка запусков.',
  'Reconnect to this same run. Read current /state generation and command receipts before resubmitting; inspect checkpoints even after evaluator completion. Explicitly pause or finalize when done. No internal agent takeover is automatic.': 'Подключайтесь к этому же запуску. Перед повторной отправкой прочитайте generation из /state и квитанции команд; проверьте вопросы даже после завершения оценки. Явно поставьте паузу или завершите запуск. Внутренний агент не подхватывает работу автоматически.',
}

export function harnessText(language, text) {
  return language === 'ru' && Object.hasOwn(russian, text) ? russian[text] : text
}
