// Loaded only when a Russian launch card is shown. Translate UI copy, never authored task data.
const copy = {
  "new run": "новый запуск",
  "Review launch proposal": "Проверьте план запуска",
  "✓ validated": "✓ проверено",
  "not validated": "не проверено",
  "Cannot start yet": "Запуск пока недоступен",
  "What this run will do": "Что будет делать этот запуск",
  "Goal": "Цель",
  "Score": "Метрика",
  "Code or data": "Код и данные",
  "May edit": "Можно менять",
  "Protected": "Защищено от правок",
  "Original data": "Исходные данные",
  "Limits": "Лимиты",
  "Validate to see effective limits.": "Проверьте план, чтобы увидеть итоговые лимиты.",
  "Proposal details are open so you can fix the highlighted fields.": "Поля плана открыты: исправьте отмеченные ошибки.",
  "Hide proposal details": "Скрыть параметры плана",
  "Edit proposal details": "Изменить параметры плана",
  "Run identity": "Название запуска",
  "Run name": "Название запуска",
  "Task and evaluation contract": "Задача и правила оценки",
  "Task source": "Источник задачи",
  "Inline task JSON": "Задача в JSON",
  "Task file": "Файл задачи",
  "Task file path": "Путь к файлу задачи",
  "Task summary": "Описание задачи",
  "Lossless task contract: goal, direction, repo/data, command, metric reader, and edit boundaries.": "Полное описание задачи: цель, направление метрики, код и данные, команда оценки, чтение результата и разрешённые правки.",
  "Runtime and budget": "Настройки и лимиты",
  "Profile": "Профиль",
  "Backend": "Режим выполнения",
  "Model": "Модель",
  "Run LLM budget (USD)": "Бюджет модели для запуска, USD",
  "0 = no limit. A lower llm_cost_limit still applies. Covers run LLM calls only.": "0 — без лимита. Меньший llm_cost_limit сохраняется. Только вызовы модели в запуске.",
  "Policy": "Стратегия поиска",
  "Card queue selection": "Выбор из очереди Cards",
  "Max nodes": "Максимум экспериментов",
  "Seeds": "Повторов с разными seed",
  "Eval parallel": "Экспериментов одновременно",
  "LLM parallel": "Вызовов модели одновременно",
  "Wall-clock budget (s)": "Время всего запуска, с",
  "Eval budget (s)": "Время одного эксперимента, с",
  "Use inherited value": "Из настроек задачи или LoopLab",
  "Invalid value — edit Advanced JSON": "Неверное значение — исправьте JSON настроек",
  "Override: Enabled": "Включить",
  "Override: Disabled": "Выключить",
  "inherit": "из настроек",
  "inherit configured model": "модель из настроек",
  "Enabled": "включено",
  "Disabled": "выключено",
  "Validated inherited value:": "Итоговое значение после проверки:",
  "Inherit resolves from task-file, saved, environment, profile, or default settings. Validate for free to see the effective value.": "Значение берётся из файла задачи, сохранённых настроек, окружения, профиля или значений по умолчанию. Бесплатная проверка покажет итоговое значение.",
  "Opt in to the Card scorer as the macro-action owner. Pinned at run start; when enabled it takes precedence over agent-driven actions.": "Передать выбор действий оценщику Cards. Фиксируется при запуске; при включении имеет приоритет над действиями агента.",
  "Concurrent evaluations; 0 = AUTO (one per detected GPU).": "Одновременных оценок; 0 = автоматически, по одной на обнаруженный GPU.",
  "Total LLM-call budget + build fan-out; 0 = launch AUTO. Positive values govern build, research, novelty, and enrichment lanes.": "Общий лимит одновременных вызовов модели и подготовок кандидатов. 0 = автоматически при запуске; положительное число ограничивает подготовку, исследование, проверку новизны и обогащение.",
  "Advanced settings JSON": "Все настройки в JSON",
  "Advanced settings": "Все настройки",
  "Lossless settings overrides": "Переопределения настроек",
  "The shortcuts above edit this same object; unlisted proposal settings are preserved.": "Поля выше меняют этот же JSON. Остальные настройки плана сохраняются.",
  "Readiness notes": "Подготовка к запуску",
  "Operator checklist only — these notes are not commands and are not executed automatically.": "Это список для проверки оператором. Эти пункты не исполняются автоматически.",
  "Setup notes": "Подготовка к запуску",
  "Warnings": "Предупреждения",
  "Validated preview": "Проверенный план в JSON",
  "Startup being observed": "Проверяем уже отправленный запуск",
  "The recovery key stays hidden and no new launch will be sent.": "Ключ восстановления скрыт. Новый запуск не отправляется.",
  "Damaged startup recovery": "Запись восстановления повреждена",
  "Its outcome cannot be trusted. Inspect the run list and provider activity before releasing this exact local fence.": "Результат этой записи не подтверждён. Перед снятием блокировки проверьте список запусков и активность провайдера.",
  "Settings need attention": "Проверьте настройки LoopLab",
  "Go to Settings": "Открыть настройки",
  "Launch review": "Условия запуска",
  "Effective launch settings": "Итоговые настройки запуска",
  "Launch settings to validate": "Настройки перед проверкой",
  "Run": "Запуск",
  "Search": "Объём поиска",
  "Parallel": "Одновременная работа",
  "Time limits": "Лимиты времени",
  "Missing run name": "Название не задано",
  "Missing task file": "Файл задачи не задан",
  "Not used (toy backend)": "Не используется в режиме toy",
  "Not configured": "Не настроена",
  "inherit (validate)": "из настроек — уточнит проверка",
  "invalid JSON": "ошибка в JSON",
  "not set": "не задано",
  "no limit": "без ограничения",
  "Auto (GPU count)": "Авто — по числу GPU",
  "default": "по умолчанию",
  "unknown": "неизвестно",
  "build · no shared provider cap": "подготовок · общего лимита вызовов модели нет",
  "Auto build · no shared provider cap": "Автоматическая подготовка · общего лимита вызовов модели нет",
  "build/shared cap": "подготовок / общий лимит вызовов модели",
  "nodes": "экспериментов",
  "seeds": "seed",
  "eval": "оценка",
  "run": "весь запуск",
  "Experiments:": "Экспериментов:",
  "Run time": "время запуска",
  "s": " с",
  "Validate is free:": "Проверка бесплатна:",
  "it makes no model/provider call and resolves inherited values in the review above.": "не вызывает модель и уточняет итоговые значения в условиях выше.",
  "Provider cost:": "Расходы на модель:",
  "Toy makes no built-in model/provider calls.": "Встроенный режим toy не вызывает модель у провайдера.",
  "LLM calls may incur provider cost.": "Вызовы модели могут тратить средства у провайдера.",
  "No run LLM limit configured.": "Лимит модели в запуске не задан.",
  "Run LLM limit unavailable; validate with the current server.": "Лимит модели недоступен. Проверьте план на актуальном сервере.",
  "Validate to resolve the inherited run LLM limit.": "Проверьте план, чтобы уточнить лимит модели с учётом наследуемых настроек.",
  "This limit excludes Assistant chat, external-client models and experiment/upstream compute.": "Лимит не покрывает чат ассистента, модели внешнего клиента и вычисления экспериментов и upstream.",
  "Unpriced calls leave spend unknown; costs can exceed the limit before a call settles. This is not a provider bill or compute cap.": "Без цен расходы неизвестны; до завершения вызова возможен перерасход. Это не счёт провайдера и не лимит вычислений.",
  "Reset proposal": "Сбросить план",
  "Open started run": "Открыть запуск",
  "Release after inspection": "Снять блокировку после проверки",
  "Checking…": "Проверяем…",
  "Waiting for Start…": "Ждём подтверждения запуска…",
  "Check startup": "Проверить запуск",
  "Validating…": "Проверяем план…",
  "Validate again — free": "Проверить снова — бесплатно",
  "Validate — free": "Проверить — бесплатно",
  "Starting…": "Запускаем…",
  "Start run": "Начать запуск",
  "Source": "Источник",
  "Task": "Задача",
  "Type": "Тип",
  "Direction": "Направление метрики",
  "Evaluation": "Оценка",
  "Metric": "Метрика",
  "Validation": "Проверка",
  "Startup identity": "Идентификатор запуска",
  "Chat context": "Контекст чата",
  "Startup recovery": "Восстановление запуска",
  "Before launch": "Перед запуском",
  "No task file selected": "Файл задачи не выбран",
  "Fix the JSON to preview this task": "Исправьте JSON, чтобы увидеть описание задачи",
  "Not selected": "Не выбран",
  "Validate to inspect the goal, score, and edit rules in this file.": "Проверьте план, чтобы увидеть цель, метрику и разрешённые правки из этого файла.",
  "Fix the task JSON before review.": "Исправьте JSON задачи перед проверкой.",
  "higher is better": "больше — лучше",
  "lower is better": "меньше — лучше",
  "direction resolved by evaluator": "направление определит оценщик",
  "direction not stated": "направление не указано",
  "Not stated in the task.": "Не указана в задаче.",
  "Metric not explicitly stated": "Метрика явно не указана",
  "No external path stated in the task.": "Внешние пути не указаны в задаче.",
  "not stated": "не указано",
  "No protected paths listed in the task.": "Защищённые пути не указаны в задаче.",
  "editable; others read-only.": "можно менять; остальные — только читать.",
  "No editable originals declared.": "Редактируемые исходные данные не заявлены."
}

export default text => Object.hasOwn(copy, text) ? copy[text] : text
