"""The PROV export carries the run's CLAIMS, their evidence and the verifier's verdict (doc 52 row 30).

`GET /api/runs/{id}/prov` exported solution entities, experiment activities and two agents — what
the SEARCH did — and nothing about what the run CONCLUDED, although `research_completed` already
holds each memo's claims, the exact-span evidence ids they are bound to, and D8's per-claim verdict.
A reviewer's question ("what does this run claim, and on what evidence?") had no answer in the one
surface whose entire job is provenance.

These drive the route over a real folded log rather than pinning strings: the memo goes through the
same sanitizer the fold applies, so what the graph shows is what a run would actually publish.
"""
from __future__ import annotations

import pytest

pytest.importorskip("fastapi")

from fastapi.testclient import TestClient  # noqa: E402

from looplab.core.research_record import evidence_item  # noqa: E402
from looplab.events.eventstore import EventStore  # noqa: E402
from looplab.serve.server import make_app  # noqa: E402

EVIDENCE = evidence_item(tool="web_search", locator="https://arxiv.org/abs/2608.18312",
                         result="claims-as-individuals is the profile", turn=1)
ORPHAN_EVIDENCE = evidence_item(tool="web_search", locator="https://example/gone",
                                result="a span whose ledger row never landed", turn=2)


def _run(tmp_path, memo, *, claims_extra=()):
    rd = tmp_path / "demo"
    rd.mkdir(parents=True)
    store = EventStore(rd / "events.jsonl")
    store.append("run_started", {"run_id": "demo", "task_id": "t", "goal": "g", "direction": "min"})
    for node_id in (0, 1):
        store.append("node_created", {"node_id": node_id, "parent_ids": [], "operator": "improve",
                                      "idea": {"operator": "improve", "params": {"x": node_id},
                                               "rationale": "r"}})
        store.append("node_evaluated", {"node_id": node_id, "metric": 1.0 + node_id})
    store.append("research_completed", {"memo": memo, "at_node": 1, "trigger": "cadence",
                                        "served_manual": False})
    for extra in claims_extra:
        store.append("research_completed", {"memo": extra, "at_node": 1, "trigger": "cadence",
                                            "served_manual": False})
    return TestClient(make_app(tmp_path)).get("/api/runs/demo/prov").json()


def _memo(claims, *, verdicts=None, evidence=(EVIDENCE,)):
    memo = {"summary": "what the pass concluded", "at_node": 1, "trigger": "cadence",
            "claims": claims, "evidence": list(evidence)}
    if verdicts is not None:
        memo["verification"] = {"verdicts": verdicts, "method": "llm",
                                "unsupported": sum(1 for v in verdicts
                                                   if v.get("verdict") == "unsupported"),
                                "total_verdicts": len(verdicts), "omitted_verdicts": 0}
    return memo


def _claims(graph):
    return {k: v for k, v in graph["entity"].items() if v.get("prov:type") == "ll:Claim"}


def _derivations(graph, entity):
    return {d["prov:usedEntity"] for d in graph["wasDerivedFrom"].values()
            if d["prov:generatedEntity"] == entity}


def test_a_claim_is_an_entity_derived_from_its_evidence_and_the_experiments_it_cites(tmp_path):
    graph = _run(tmp_path, _memo(
        [{"statement": "operator improve beats draft", "node_ids": [0, 1],
          "evidence_ids": [EVIDENCE["id"]], "urls": ["https://arxiv.org/abs/2608.18312"]}],
        verdicts=[{"statement": "operator improve beats draft", "verdict": "supported",
                   "note": "both nodes evaluated"}]))
    claims = _claims(graph)
    assert len(claims) == 1, claims
    cid, claim = next(iter(claims.items()))
    assert claim["ll:statement"] == "operator improve beats draft"
    assert claim["ll:verdict"] == "supported" and claim["ll:verdict_binding"] == "aligned"
    assert claim["ll:cited_nodes"] == [0, 1] and claim["ll:cited_missing_nodes"] == []
    # generated by the pass that made it …
    activity = graph["wasGeneratedBy"][f"wgb:{cid}"]["prov:activity"]
    assert activity.startswith("memo:") and activity in graph["activity"]
    # … and derived from BOTH the experiments it cites and the exact span it is bound to
    assert _derivations(graph, cid) == {"sol:0:0", "sol:1:0", f"evidence:{EVIDENCE['id']}"}
    evidence = graph["entity"][f"evidence:{EVIDENCE['id']}"]
    assert evidence["prov:type"] == "ll:Evidence"
    assert evidence["ll:quote"] == EVIDENCE["quote"] and evidence["ll:tool"] == "web_search"
    # the memo activity is the researcher's, and says how the claims were checked
    association = next(v for v in graph["wasAssociatedWith"].values()
                       if v["prov:activity"] == activity)
    assert association["prov:role"] == "ll:researcher"
    assert graph["activity"][activity]["ll:verification_method"] == "llm"
    assert graph["activity"][activity]["ll:unsupported_claims"] == 0


def test_a_claim_citing_an_experiment_the_run_does_not_have_names_the_gap(tmp_path):
    """A model can cite an experiment id that never existed (or that a reset removed). The export
    keeps the citation and says it is unresolved — inventing `sol:99:0` would publish an
    unresolvable reference as if it were lineage."""
    graph = _run(tmp_path, _memo([{"statement": "node 99 was best", "node_ids": [1, 99],
                                   "evidence_ids": []}]))
    cid, claim = next(iter(_claims(graph).items()))
    assert claim["ll:cited_nodes"] == [1, 99] and claim["ll:cited_missing_nodes"] == [99]
    assert _derivations(graph, cid) == {"sol:1:0"}
    assert "sol:99:0" not in graph["entity"]


def test_an_evidence_id_with_no_ledger_row_is_kept_as_unrecorded(tmp_path):
    """The BINDING outlives its span: a memo folded before the evidence ledger existed still names
    the id it was bound to, and the graph says the row is missing rather than dropping the edge."""
    graph = _run(tmp_path, _memo(
        [{"statement": "held", "node_ids": [0],
          "evidence_ids": [EVIDENCE["id"], ORPHAN_EVIDENCE["id"]]}]))
    cid = next(iter(_claims(graph)))
    orphan = graph["entity"][f"evidence:{ORPHAN_EVIDENCE['id']}"]
    assert orphan["ll:lifecycle"] == "unrecorded" and "ll:quote" not in orphan
    assert f"evidence:{ORPHAN_EVIDENCE['id']}" in _derivations(graph, cid)


def test_a_claim_never_wears_another_claims_verdict(tmp_path):
    """Verdicts are positional AND carry their own statement, so the binding is checkable. A verdict
    list that does not line up (a memo capped after verification, a hand-edited log) must export the
    binding failure — the alternative is claim *i*'s text under claim *j*'s verdict, in the surface
    a reviewer trusts most."""
    graph = _run(tmp_path, _memo(
        [{"statement": "first claim", "node_ids": [0], "evidence_ids": []},
         {"statement": "second claim", "node_ids": [1], "evidence_ids": []}],
        verdicts=[{"statement": "a statement from some other memo", "verdict": "unsupported",
                   "note": ""}]))
    by_statement = {c["ll:statement"]: c for c in _claims(graph).values()}
    assert by_statement["first claim"]["ll:verdict_binding"] == "unmatched"
    assert "ll:verdict" not in by_statement["first claim"]
    assert by_statement["second claim"]["ll:verdict_binding"] == "unmatched"
    # a memo with no verification at all is distinguishable from one whose verdict did not bind
    plain = _run(tmp_path / "b", _memo([{"statement": "unchecked", "node_ids": [0],
                                         "evidence_ids": []}]))
    assert next(iter(_claims(plain).values()))["ll:verdict_binding"] == "not_verified"


def test_the_verdict_binds_by_statement_when_the_positions_slipped(tmp_path):
    """One unique statement match is still a sound bind — that is the case a cap creates."""
    graph = _run(tmp_path, _memo(
        [{"statement": "only claim", "node_ids": [0], "evidence_ids": []}],
        verdicts=[{"statement": "a retired claim", "verdict": "unsupported", "note": ""},
                  {"statement": "only claim", "verdict": "supported", "note": "checked"}]))
    claim = next(iter(_claims(graph).values()))
    assert claim["ll:verdict"] == "supported" and claim["ll:verdict_binding"] == "statement"


def test_a_run_with_more_claims_than_the_cap_says_what_it_cut(tmp_path):
    """A silently truncated provenance export is worse than a short one: the graph carries the count."""
    big = [_memo([{"statement": f"claim {i}·{j}", "node_ids": [0], "evidence_ids": []}
                  for j in range(20)], evidence=()) for i in range(30)]
    graph = _run(tmp_path, big[0], claims_extra=big[1:])
    assert len(_claims(graph)) == 400
    assert graph["ll:omitted"]["claims"] == 30 * 20 - 400
    assert graph["ll:omitted"]["memos"] >= 1


def test_the_search_half_of_the_graph_is_unchanged_by_a_run_with_no_research(tmp_path):
    """A run that never thought hard exports exactly the graph it always did — no empty claim keys."""
    rd = tmp_path / "demo"
    rd.mkdir(parents=True)
    store = EventStore(rd / "events.jsonl")
    store.append("run_started", {"run_id": "demo", "task_id": "t", "goal": "g", "direction": "min"})
    store.append("node_created", {"node_id": 0, "parent_ids": [], "operator": "draft",
                                  "idea": {"operator": "draft", "params": {}, "rationale": ""}})
    store.append("node_evaluated", {"node_id": 0, "metric": 1.0})
    graph = TestClient(make_app(tmp_path)).get("/api/runs/demo/prov").json()
    assert set(graph["entity"]) == {"sol:0:0"} and "ll:omitted" not in graph
    assert not [a for a in graph["activity"] if a.startswith("memo:")]
