import React, { lazy, useCallback, useEffect, useRef, useState } from "react";
import OwnerAuth from "./OwnerAuth.mjs";
import LazyBoundary from "./LazyBoundary.mjs";
import OwnerWorkspace from "./OwnerWorkspace.mjs";
import { deadlineGet, reviewTokenFromLocation } from "./api.mjs";
import { initTheme } from "./ThemeSwitcher.mjs";
import { initFx } from "./fx.mjs";
import { initDensity } from "./DensityToggle.mjs";
import { routeHashPath } from "./runRouteState.mjs";
import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
const RunList = lazy(() => import("./RunList.jsx"));
const RunView = lazy(() => import("./RunView.jsx"));
const Settings = lazy(() => import("./Settings.jsx"));
const ResearchAtlas = lazy(() => import("./ResearchAtlas.jsx"));
const SharedAssistant = lazy(() => import("./SharedAssistant.jsx"));
initTheme();
initFx();
initDensity();
// Tiny hash router: #/run/<id> opens a run; #/settings and #/atlas open owner tools. The legacy
// #/research-atlas alias is replaced in place so links generated by the UI have one canonical form. The
// assistant is NOT a route anymore — it's one persistent component (AssistantBar) with three views (bar/drawer/full) that
// stays mounted across every route, so its conversation is never reset by navigation.
const safeDecode = (s) => {
	try {
		return decodeURIComponent(s);
	} catch {
		return s;
	}
};
function parseHash() {
	if (/\/review\/?$/.test(location.pathname)) return {
		view: "review",
		token: reviewTokenFromLocation()
	};
	const h = routeHashPath(location.hash);
	if (h === "#/settings") return { view: "settings" };
	if (h === "#/research-atlas") return {
		view: "research-atlas",
		canonicalHash: "#/atlas"
	};
	if (h === "#/atlas") return { view: "research-atlas" };
	const sh = h.match(/^#\/assistant\/shared\/(.+)$/);
	if (sh) return {
		view: "shared",
		id: safeDecode(sh[1])
	};
	const m = h.match(/^#\/run\/(.+)$/);
	return m ? {
		view: "run",
		id: safeDecode(m[1])
	} : { view: "list" };
}
const LIST_HISTORY_KEY = "looplab.listNavigation";
const LIST_HISTORY_CACHE_LIMIT = 128;
const LIST_ORIGIN_CONTROLS = new Set(["settings"]);
const listHistoryCache = new Map();
let listHistorySequence = 0;
const normalizeListOriginControl = (value) => LIST_ORIGIN_CONTROLS.has(value) ? value : null;
function rawListHistory() {
	const state = history.state;
	if (!state || typeof state !== "object" || Array.isArray(state)) return null;
	const saved = state[LIST_HISTORY_KEY];
	return saved && typeof saved === "object" && !Array.isArray(saved) ? saved : null;
}
function nextListHistoryEntryId() {
	listHistorySequence += 1;
	return `${Date.now().toString(36)}-${listHistorySequence.toString(36)}`;
}
function cacheListHistory(entryId, navigation) {
	if (!entryId || !navigation || typeof navigation !== "object" || Array.isArray(navigation)) return;
	listHistoryCache.delete(entryId);
	listHistoryCache.set(entryId, navigation);
	while (listHistoryCache.size > LIST_HISTORY_CACHE_LIMIT) {
		listHistoryCache.delete(listHistoryCache.keys().next().value);
	}
}
function readListHistory() {
	const saved = rawListHistory();
	if (!saved) return null;
	const entryId = typeof saved.entryId === "string" && saved.entryId && saved.entryId.length <= 128 ? saved.entryId : null;
	const candidate = entryId && listHistoryCache.get(entryId) || saved.navigation;
	const navigation = candidate && typeof candidate === "object" && !Array.isArray(candidate) ? candidate : null;
	return {
		...saved,
		entryId,
		navigation,
		originRunId: typeof saved.originRunId === "string" && saved.originRunId ? saved.originRunId : null,
		originControl: normalizeListOriginControl(saved.originControl)
	};
}
function writeListHistory(navigation, originRunId = null, originControl = null) {
	if (!navigation || typeof navigation !== "object" || Array.isArray(navigation)) return;
	try {
		const state = history.state && typeof history.state === "object" && !Array.isArray(history.state) ? history.state : {};
		const current = rawListHistory();
		const entryId = typeof current?.entryId === "string" && current.entryId && current.entryId.length <= 128 ? current.entryId : nextListHistoryEntryId();
		cacheListHistory(entryId, navigation);
		history.replaceState({
			...state,
			[LIST_HISTORY_KEY]: {
				navigation,
				originRunId: typeof originRunId === "string" && originRunId ? originRunId : null,
				originControl: normalizeListOriginControl(originControl),
				entryId
			}
		}, "", location.href);
	} catch {}
}
function cacheCurrentListHistory(navigation, originRunId = null, originControl = null) {
	const current = rawListHistory();
	const entryId = typeof current?.entryId === "string" && current.entryId && current.entryId.length <= 128 ? current.entryId : null;
	if (entryId) {
		cacheListHistory(entryId, navigation);
		return;
	}
	writeListHistory(navigation, originRunId, originControl);
}
function ReviewRoute({ token }) {
	const [resource, setResource] = useState({
		status: "loading",
		error: ""
	});
	const [retry, setRetry] = useState(0);
	useEffect(() => {
		let active = true;
		if (!token) {
			setResource({
				status: "gone",
				error: "Review link incomplete or invalid. Ask the owner for a new link."
			});
			return () => {
				active = false;
			};
		}
		setResource({
			status: "loading",
			error: ""
		});
		const timed = deadlineGet("/api/review", 12e3);
		timed.promise.then((data) => {
			if (active) setResource({
				status: "ready",
				data,
				error: ""
			});
		}).catch((error) => {
			if (!active) return;
			const gone = [
				401,
				404,
				410
			].includes(error?.status);
			setResource({
				status: gone ? "gone" : "error",
				error: gone ? "Review link invalid, expired, or revoked. Ask the owner for a new link." : "Review link unavailable. Retry."
			});
		});
		return () => {
			active = false;
			timed.controller.abort();
		};
	}, [token, retry]);
	useEffect(() => {
		const frame = requestAnimationFrame(() => {
			if (!document.querySelector("[aria-modal=\"true\"]")) document.querySelector("[data-route-main]")?.focus();
		});
		return () => cancelAnimationFrame(frame);
	}, [resource.status]);
	if (resource.status !== "ready") return /* @__PURE__ */ _jsx("main", {
		className: "auth-gate",
		"data-route-main": true,
		tabIndex: -1,
		"aria-live": "polite",
		children: /* @__PURE__ */ _jsxs("div", {
			className: "auth-card",
			children: [
				/* @__PURE__ */ _jsx("div", {
					className: "auth-mark",
					"aria-hidden": "true",
					children: resource.status === "gone" ? "×" : "◉"
				}),
				/* @__PURE__ */ _jsx("h1", { children: resource.status === "loading" ? "Opening review…" : resource.status === "gone" ? "Review link unavailable" : "Could not open review" }),
				/* @__PURE__ */ _jsx("p", { children: resource.status === "loading" ? "Validating this read-only capability." : resource.error }),
				resource.status === "error" && /* @__PURE__ */ _jsx("button", {
					className: "btn primary",
					onClick: () => setRetry((n) => n + 1),
					children: "Retry"
				})
			]
		})
	});
	const reviewKey = `${resource.data.id || token}:${resource.data.run_id}`;
	return /* @__PURE__ */ _jsx(LazyBoundary, {
		label: "run review",
		mode: "route",
		focusOnReady: true,
		resetKey: reviewKey,
		children: /* @__PURE__ */ _jsx(RunView, {
			runId: resource.data.run_id,
			onBack: null,
			reviewMode: true,
			reviewMeta: resource.data
		}, reviewKey)
	});
}
function RouteFocus({ label, routeKey, children, autoFocus = true }) {
	useEffect(() => {
		document.title = `${label} · LoopLab`;
		if (!autoFocus) return undefined;
		const frame = requestAnimationFrame(() => {
			if (!document.querySelector("[aria-modal=\"true\"]")) document.querySelector("[data-route-main]")?.focus();
		});
		return () => cancelAnimationFrame(frame);
	}, [
		routeKey,
		label,
		autoFocus
	]);
	return /* @__PURE__ */ _jsxs(_Fragment, { children: [/* @__PURE__ */ _jsx("div", {
		className: "sr-only",
		role: "status",
		"aria-live": "polite",
		"aria-atomic": "true",
		children: label
	}), children] });
}
export default function App() {
	const initialListHistoryRef = useRef();
	if (initialListHistoryRef.current === undefined) {
		initialListHistoryRef.current = readListHistory() || null;
	}
	const listNavigationRef = useRef(initialListHistoryRef.current?.navigation || null);
	const listOriginRunRef = useRef(initialListHistoryRef.current?.originRunId || null);
	const listOriginControlRef = useRef(initialListHistoryRef.current?.originControl || null);
	const [route, setRoute] = useState(parseHash());
	useEffect(() => {
		const on = () => {
			const next = parseHash();
			const saved = readListHistory();
			if (saved?.navigation) {
				const keepsListOrigin = next.view === "list" || next.view === "settings";
				const originRunId = next.view === "run" ? next.id : keepsListOrigin ? saved.originRunId : null;
				const originControl = keepsListOrigin ? saved.originControl : null;
				listNavigationRef.current = saved.navigation;
				listOriginRunRef.current = originRunId;
				listOriginControlRef.current = originControl;
				// Materialize any newer entry-cache snapshot into the destination entry too. This keeps a
				// subsequent reload exact and normalizes origins copied by direct hash navigation.
				writeListHistory(saved.navigation, originRunId, originControl);
			} else if (listNavigationRef.current) {
				const keepsListOrigin = next.view === "list" || next.view === "settings";
				const originRunId = next.view === "run" ? next.id : keepsListOrigin ? listOriginRunRef.current : null;
				const originControl = keepsListOrigin ? listOriginControlRef.current : null;
				listOriginRunRef.current = originRunId;
				listOriginControlRef.current = originControl;
				writeListHistory(listNavigationRef.current, originRunId, originControl);
			}
			setRoute(next);
		};
		window.addEventListener("hashchange", on);
		window.addEventListener("popstate", on);
		return () => {
			window.removeEventListener("hashchange", on);
			window.removeEventListener("popstate", on);
		};
	}, []);
	useEffect(() => {
		if (!route.canonicalHash || location.hash === route.canonicalHash) return;
		try {
			history.replaceState(history.state, "", route.canonicalHash);
		} catch {
			// The legacy alias already renders its correct destination. If History is throttled, use a
			// same-document replacement when available and never let canonicalization crash the route.
			try {
				location.replace(route.canonicalHash);
			} catch {}
		}
		if (location.hash === route.canonicalHash) setRoute(parseHash());
	}, [route.canonicalHash]);
	const routeLabel = route.view === "run" ? `Run ${route.id}` : route.view === "settings" ? "Settings" : route.view === "research-atlas" ? "Research Atlas preview" : route.view === "shared" ? "Shared Assistant chat" : route.view === "review" ? "Read-only run review" : "Runs";
	const rememberListNavigation = useCallback((snapshot, options = null) => {
		if (snapshot && typeof snapshot === "object" && !Array.isArray(snapshot)) {
			listNavigationRef.current = snapshot;
			if (route.view === "list") {
				const current = readListHistory();
				const originRunId = current && Object.prototype.hasOwnProperty.call(current, "originRunId") ? current.originRunId : listOriginRunRef.current;
				const originControl = current && Object.prototype.hasOwnProperty.call(current, "originControl") ? current.originControl : listOriginControlRef.current;
				if (options?.persist === false) cacheCurrentListHistory(snapshot, originRunId, originControl);
				else writeListHistory(snapshot, originRunId, originControl);
			}
		}
	}, [route.view]);
	const finishListRestore = useCallback((snapshot) => {
		if (snapshot && typeof snapshot === "object" && !Array.isArray(snapshot)) {
			listNavigationRef.current = snapshot;
		}
		listOriginRunRef.current = null;
		listOriginControlRef.current = null;
		writeListHistory(listNavigationRef.current, null, null);
	}, []);
	const navigateWithListState = useCallback((hash, snapshot, originRunId = null, originControl = null) => {
		const navigation = snapshot || listNavigationRef.current;
		if (navigation) {
			listNavigationRef.current = navigation;
			listOriginRunRef.current = originRunId;
			listOriginControlRef.current = normalizeListOriginControl(originControl);
			writeListHistory(navigation, originRunId, originControl);
		}
		location.hash = hash;
		if (navigation) writeListHistory(navigation, originRunId, originControl);
	}, []);
	const open = useCallback((id, snapshot, href = null) => {
		const runId = String(id);
		const target = typeof href === "string" && href.startsWith("#/run/") ? href : `#/run/${encodeURIComponent(runId)}`;
		navigateWithListState(target, snapshot, runId);
	}, [navigateWithListState]);
	const back = useCallback(() => {
		location.hash = "";
		if (listNavigationRef.current) {
			writeListHistory(listNavigationRef.current, listOriginRunRef.current, listOriginControlRef.current);
		}
	}, []);
	const settings = useCallback((snapshot) => {
		navigateWithListState("#/settings", snapshot, null, "settings");
	}, [navigateWithListState]);
	const researchAtlas = useCallback((snapshot) => {
		navigateWithListState("#/atlas", snapshot, null);
	}, [navigateWithListState]);
	const restoreListNavigation = route.view === "list" && !!listNavigationRef.current;
	// Public review/share views own the whole screen and return before any owner-plane component mounts.
	// Everywhere else (list / run / settings) the persistent assistant and attention inbox stay available.
	let content;
	const routeKey = `${route.view}:${route.id || route.token || ""}`;
	if (route.view === "review") return /* @__PURE__ */ _jsx(RouteFocus, {
		label: routeLabel,
		routeKey,
		children: /* @__PURE__ */ _jsx(ReviewRoute, { token: route.token }, route.token || "invalid-review")
	});
	// The shared read-only chat is a PUBLIC surface: the backend serves /api/assistant/shared/ WITHOUT
	// the owner token (server.py::_unauth_api_ok), so it must bypass the OwnerAuth unlock gate exactly
	// like the review route. Falling through into <OwnerAuth> made a token-protected deployment show
	// recipients the "Unlock LoopLab controls" screen instead of the chat, defeating the share link.
	if (route.view === "shared") return /* @__PURE__ */ _jsx(RouteFocus, {
		label: routeLabel,
		routeKey,
		children: /* @__PURE__ */ _jsx(LazyBoundary, {
			label: "shared Assistant chat",
			mode: "route",
			focusOnReady: true,
			resetKey: routeKey,
			children: /* @__PURE__ */ _jsx(SharedAssistant, { sid: route.id })
		}, routeKey)
	});
	if (route.view === "run") content = /* @__PURE__ */ _jsx(LazyBoundary, {
		label: `run ${route.id}`,
		mode: "route",
		focusOnReady: true,
		resetKey: routeKey,
		children: /* @__PURE__ */ _jsx(RunView, {
			runId: route.id,
			onBack: back
		}, route.id)
	});
	else if (route.view === "settings") content = /* @__PURE__ */ _jsx(LazyBoundary, {
		label: "settings",
		mode: "route",
		focusOnReady: true,
		resetKey: routeKey,
		children: /* @__PURE__ */ _jsx(Settings, { onBack: back })
	});
	else if (route.view === "research-atlas") content = /* @__PURE__ */ _jsx(LazyBoundary, {
		label: "Research Atlas preview",
		mode: "route",
		focusOnReady: true,
		resetKey: routeKey,
		children: /* @__PURE__ */ _jsx(ResearchAtlas, { onBack: back })
	});
	else content = /* @__PURE__ */ _jsx(LazyBoundary, {
		label: "runs",
		mode: "route",
		focusOnReady: !restoreListNavigation,
		resetKey: routeKey,
		children: /* @__PURE__ */ _jsx(RunList, {
			initialNavigationState: listNavigationRef.current,
			restoreFocusRunId: listOriginRunRef.current,
			restoreFocusControl: listOriginControlRef.current,
			onNavigationStateChange: rememberListNavigation,
			onNavigationRestored: finishListRestore,
			onOpen: open,
			onSettings: settings,
			onResearchAtlas: researchAtlas
		})
	});
	return /* @__PURE__ */ _jsx(OwnerAuth, {
		label: routeLabel,
		children: /* @__PURE__ */ _jsx(RouteFocus, {
			label: routeLabel,
			routeKey,
			autoFocus: !restoreListNavigation,
			children: /* @__PURE__ */ _jsx(OwnerWorkspace, {
				route,
				children: content
			})
		})
	});
}
