// The browser half of the run stream's state deltas (doc 52 row 29): the ops apply exactly as the
// server's differ means them, and a delta is refused — never guessed — when it is not against the
// snapshot the client holds.
import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

import { STATE_DELTA_VERSION, applyOps, applyStateDelta, deltaApplies } from '../src/stateDelta.js'

const held = {
  state: { nodes: { 0: { metric: null, status: 'pending' } }, best_node_id: null, rows: [1, 2] },
  seq: 4, generation: 'g'.repeat(64), event_count: 5,
}
const frame = (ops, extra = {}) => ({
  version: STATE_DELTA_VERSION, base_seq: 4, seq: 5, generation: held.generation, event_count: 6,
  ops, ...extra,
})

test('ops set leaves, add keys, replace lists whole and delete keys, without touching the base', () => {
  const before = JSON.stringify(held)
  const next = applyOps(held, [
    ['set', ['state', 'nodes', '0', 'metric'], 0.5],
    ['set', ['state', 'nodes', '0', 'status'], 'evaluated'],
    ['set', ['state', 'nodes', '1'], { status: 'pending' }],
    ['set', ['state', 'rows'], [1, 2, 3]],
    ['del', ['state', 'best_node_id']],
    ['set', ['seq'], 5],
  ])
  assert.deepEqual(next.state, {
    nodes: { 0: { metric: 0.5, status: 'evaluated' }, 1: { status: 'pending' } }, rows: [1, 2, 3],
  })
  assert.equal(next.seq, 5)
  assert.equal(JSON.stringify(held), before, 'the held payload is never mutated')
})

test('a delta applies only to the exact snapshot it was computed against', () => {
  const ops = [['set', ['seq'], 5], ['set', ['event_count'], 6]]
  const next = applyStateDelta(held, frame(ops))
  assert.equal(next.seq, 5)
  assert.equal(applyStateDelta(held, frame(ops, { base_seq: 3 })), null, 'wrong base')
  assert.equal(applyStateDelta(held, frame(ops, { version: 2 })), null, 'unknown version')
  assert.equal(applyStateDelta(held, frame([['set', ['seq'], 7]])), null, 'the ops must land on the declared seq')
  assert.equal(applyStateDelta(held, frame([['mov', ['seq'], 5]])), null, 'a malformed op')
  assert.equal(applyStateDelta(null, frame(ops)), null, 'nothing held yet')
  assert.equal(deltaApplies(frame(ops), 4), true)
  assert.equal(deltaApplies({ ops }, 4), false)
})

test('a root set replaces the whole payload and a root delete is refused', () => {
  const next = applyOps(held, [['set', [], { seq: 9, state: {} }]])
  assert.deepEqual(next, { seq: 9, state: {} })
  assert.throws(() => applyOps(held, [['del', []]]))
})

// ---------------------------------------------------------------------------------------------
// THE SHARED FIXTURE and the key semantics (review 2026-09-22, UI-03). This module claimed to apply
// the ops "with the same rules" as `looplab/events/state_delta.py`, and on one key it did not: the
// walk read `node[key]` (inherited properties included) and assigned leaves with `node[leaf] = …`, so
// a server-legal delta setting `…agent_report.__proto__` RE-PARENTED the object instead of adding a
// key (dropped from the snapshot), and the next delta — `…agent_report.__proto__.status` — walked
// into `Object.prototype` and wrote `status` onto every object in the operator's tab. Python treats
// `__proto__` as the ordinary dict key it is. `tests/fixtures/state_delta_cases.json` is generated by
// `tests/test_state_delta.py` from the Python half's own tables and ops; the Python suite refuses a
// stale file and this one applies every row, so the halves cannot drift apart again unnoticed.
// ---------------------------------------------------------------------------------------------

const FIXTURE = JSON.parse(readFileSync(
  new URL('../../tests/fixtures/state_delta_cases.json', import.meta.url), 'utf8'))

// Run `body`, then remove anything it added to Object.prototype, so a regression here fails THIS
// test with its own message instead of poisoning every assertion after it in the process.
const withPrototypeGuard = body => {
  const before = new Set(Object.getOwnPropertyNames(Object.prototype))
  try { body() } finally {
    for (const name of Object.getOwnPropertyNames(Object.prototype)) {
      if (!before.has(name)) delete Object.prototype[name]
    }
  }
}

test('every row of the shared fixture applies exactly as the Python differ means it', () => {
  const { cases } = FIXTURE
  assert.ok(cases.length >= 20, 'the fixture read too small to be the real table')
  assert.ok(cases.some(({ deltas }) => JSON.stringify(deltas).includes('"__proto__"')),
    'the fixture must carry the __proto__ rows it exists for')
  const prototypeBefore = Object.getOwnPropertyNames(Object.prototype).sort()
  withPrototypeGuard(() => {
    for (const { name, base, deltas, expected } of cases) {
      const frozen = JSON.stringify([base, deltas])
      let current = base
      for (const ops of deltas) current = applyOps(current, ops)
      assert.deepEqual(current, expected, name)
      assert.equal(JSON.stringify([base, deltas]), frozen,
        `${name}: neither the held payload nor the frame may be mutated`)
    }
    assert.deepEqual(Object.getOwnPropertyNames(Object.prototype).sort(), prototypeBefore,
      'a delta wrote into Object.prototype')
  })
  assert.deepEqual(Object.keys(Object.prototype), [])
  assert.equal(({}).status, undefined)
  assert.equal(({}).polluted, undefined)
})

test('the reviewer\'s chain through the stream path: the key is data and nothing is polluted', () => {
  // The same two frames the reviewer drove, through `applyStateDelta` (what `useRunState` calls).
  const { base, deltas, expected } = FIXTURE.cases.find(row => row.name.startsWith("the reviewer's chain"))
  withPrototypeGuard(() => {
    let current = base
    for (const [i, ops] of deltas.entries()) {
      current = applyStateDelta(current, {
        version: STATE_DELTA_VERSION, base_seq: current.seq, seq: current.seq + 1, ops,
        generation: 'g'.repeat(64), event_count: i + 2,
      })
      assert.ok(current, `delta ${i + 1} must apply`)
    }
    assert.deepEqual(current, expected)
    assert.deepEqual(Object.keys(current.state.nodes['3'].agent_report), ['__proto__'])
    assert.equal(Object.getPrototypeOf(current.state.nodes['3'].agent_report), Object.prototype)
    assert.equal(({}).status, undefined, 'Object.prototype.status was written')
  })
})

test('a key the held payload lacks is created EMPTY, whatever the prototype chain carries', () => {
  // The walk reads OWN properties only. Copy-on-write alone would hide an inherited read while
  // Object.prototype is clean (a copy of it is `{}`), so this pins the case where it is not — some
  // other script in the tab already put an enumerable key there — and the missing `__proto__` key
  // must still be created empty, as the Python half creates it, never as a copy of the chain.
  const row = FIXTURE.cases.find(c => c.name === 'a path through a missing __proto__ key creates the key')
  withPrototypeGuard(() => {
    Object.prototype.injected = 'x' // eslint-disable-line no-extend-native
    assert.deepEqual(applyOps(row.base, row.deltas[0]), row.expected)
  })
})

test('only the dicts an op writes through are copied: every untouched subtree keeps its identity', () => {
  // Every frame used to deep-clone every dict of the held payload, so a delta that moved one node's
  // metric handed React a new object for every node, card and memo of the run and no downstream
  // identity memo could survive a frame. Copy-on-write along each op's path keeps what did not move.
  const base = {
    seq: 4, generation: 'g'.repeat(64),
    state: {
      nodes: { 0: { metric: null, status: 'pending', idea: { params: { x: 1 } } },
               1: { metric: 0.2, status: 'evaluated' } },
      cards: { c1: { statement: 's' } }, rows: [1, 2],
    },
  }
  const before = JSON.stringify(base)
  const next = applyOps(base, [
    ['set', ['state', 'nodes', '0', 'metric'], 0.5],
    ['set', ['state', 'nodes', '0', 'status'], 'evaluated'],
    ['set', ['seq'], 5],
  ])
  assert.deepEqual(next.state.nodes[0], { metric: 0.5, status: 'evaluated', idea: { params: { x: 1 } } })
  assert.equal(next.seq, 5)
  for (const [moved, was] of [[next, base], [next.state, base.state], [next.state.nodes, base.state.nodes],
                              [next.state.nodes[0], base.state.nodes[0]]]) {
    assert.notEqual(moved, was, 'a dict on a written path is a copy')
  }
  assert.equal(next.state.nodes[1], base.state.nodes[1], 'an untouched node keeps its identity')
  assert.equal(next.state.nodes[0].idea, base.state.nodes[0].idea, 'an untouched child of a written dict too')
  assert.equal(next.state.cards, base.state.cards)
  assert.equal(next.state.rows, base.state.rows)
  assert.equal(JSON.stringify(base), before, 'the held payload is never mutated')
  assert.equal(applyOps(base, []), base, 'no ops is the held payload itself, as `apply` returns `old`')
})

// A FULL-CLONE REFERENCE: the algorithm this module used before copy-on-write, with the Python
// half's key semantics (own properties only, keys defined rather than assigned). Copy-on-write is an
// optimisation of exactly this, so on any delta the two must agree — driven on seeded random trees
// and op lists over the keys that matter, including the ones a JavaScript object inherits.
const isDocument = value => !!value && typeof value === 'object' && !Array.isArray(value)
const put = (doc, key, value) => Object.defineProperty(doc, key, {
  value, writable: true, enumerable: true, configurable: true,
})
const deepClone = value => {
  if (!isDocument(value)) return value
  const out = {}
  for (const [key, child] of Object.entries(value)) put(out, key, deepClone(child))
  return out
}
function referenceApply(base, ops) {
  let root = deepClone(base)
  for (const [kind, path, value] of ops) {
    if (!path.length) { root = deepClone(value); continue }
    let node = root
    for (const key of path.slice(0, -1)) {
      let child = Object.hasOwn(node, key) ? node[key] : undefined
      if (!isDocument(child)) { child = {}; put(node, key, child) }
      node = child
    }
    if (kind === 'set') put(node, path.at(-1), deepClone(value))
    else delete node[path.at(-1)]
  }
  return root
}

const seeded = seed => () => {
  seed = (seed + 0x6D2B79F5) | 0
  let t = Math.imul(seed ^ (seed >>> 15), 1 | seed)
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296
}
const KEYS = ['a', 'b', '0', '__proto__', 'constructor', 'prototype', 'toString']
const pick = (rand, list) => list[Math.floor(rand() * list.length)]
const randomDoc = (rand, depth) => {
  const doc = {}
  for (let i = Math.floor(rand() * 4); i > 0; i -= 1) put(doc, pick(rand, KEYS), randomValue(rand, depth - 1))
  return doc
}
const randomValue = (rand, depth) => {
  const roll = rand()
  if (depth <= 0 || roll < 0.35) return pick(rand, [null, 1, 'x', true, 0.5])
  if (roll < 0.45) return [1, { a: 1 }]
  return randomDoc(rand, depth)
}
const randomOps = rand => Array.from({ length: 1 + Math.floor(rand() * 5) }, () => {
  const path = Array.from({ length: Math.floor(rand() * 4) }, () => pick(rand, KEYS))
  if (!path.length && rand() < 0.85) path.push(pick(rand, KEYS))
  if (!path.length) return ['set', [], randomDoc(rand, 2)]
  return rand() < 0.3 ? ['del', path] : ['set', path, randomValue(rand, 2)]
})

test('copy-on-write agrees with the full-clone reference on 2,000 random deltas', () => {
  const rand = seeded(20260922)
  withPrototypeGuard(() => {
    for (let i = 0; i < 2000; i += 1) {
      const base = randomDoc(rand, 3)
      const ops = randomOps(rand)
      const baseBefore = deepClone(base)
      const opsBefore = JSON.stringify(ops)
      const got = applyOps(base, ops)
      assert.deepEqual(got, referenceApply(base, ops), `case ${i}: ${opsBefore}`)
      assert.deepEqual(base, baseBefore, `case ${i}: the held payload was mutated`)
      assert.equal(JSON.stringify(ops), opsBefore, `case ${i}: the frame was mutated`)
      if (ops.some(([, path]) => !path.length)) continue
      for (const key of Object.keys(base)) {
        if (ops.some(([, path]) => path[0] === key)) continue
        assert.equal(Object.getOwnPropertyDescriptor(got, key)?.value,
          Object.getOwnPropertyDescriptor(base, key).value, `case ${i}: untouched ${key} was copied`)
      }
    }
    assert.deepEqual(Object.keys(Object.prototype), [])
  })
})
